The timeout needs to be an integer.
Fixes

```
  run_markdown --overwrite lesson7.run.md --timeout 1
Traceback (most recent call last):
  File "/home/ralsina/.virtualenvs/book/bin/run_markdown", line 11, in <module>
    load_entry_point('pyliterate==0.1', 'console_scripts', 'run_markdown')()
  File "/home/ralsina/.virtualenvs/book/lib/python3.6/site-packages/pyliterate/run_markdown.py", line 380, in main
    signal.alarm(FLAGS.timeout_seconds)
TypeError: integer argument expected, got float
```